# : Manager [[[

[mgr]
cwd = { fg = "#e6e3d5" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#70d5aa", bg = "#70d5aa" }
marker_cut      = { fg = "#bfecd9", bg = "#bfecd9" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#a4d0be", bg = "#a4d0be" }

# Count
count_copied   = { fg = "#002117", bg = "#bfecd9" }
count_cut      = { fg = "#002117", bg = "#bfecd9" }
count_selected = { fg = "#323200", bg = "#a4d0be" }

# Border
border_symbol = "│"
border_style  = { fg = "#cacb77" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#cacb77", bold = true, bg = "#14140c" }
inactive  = { fg = "#cac8a5", bg = "#14140c" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#cacb77", fg = "#323200", bold = true }
normal_alt  = { bg = "#48473a", fg = "#c9c7b6" }

# Select mode
select_main = { bg = "#cac8a5", fg = "#313219", bold = true }
select_alt  = { bg = "#48473a", fg = "#c9c7b6" }

# Unset mode
unset_main = { bg = "#a4d0be", fg = "#0a372a", bold = true }
unset_alt  = { bg = "#48473a", fg = "#c9c7b6" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#87844f" }
perm_write = { fg = "#4b9074" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#49c993" }
perm_sep   = { fg = "#b5b727" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#cacb77", bg = "#3a3a30" }
progress_error  = { fg = "#ffb4ab", bg = "#3a3a30" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3a3a30" }
cand = { fg = "#cacb77" }
rest = { fg = "#323200" }
desc = { fg = "#e6e3d5" }
separator = " ▶ "
separator_style = { fg = "#e6e3d5" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#a4d0be" }
title_warn  = { fg = "#cacb77" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#cacb77" }
active = { fg = "#a4d0be", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#cacb77" }
value  = { fg = "#e6e3d5" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#cacb77", bg = "#323200" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#cacb77" }
title   = {}
hovered = { fg = "#bfecd9", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e6e3d5" }
run    = { fg = "#e6e3d5" }
footer = { fg = "#313219", bg = "#cac8a5" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#e6e3d5" },
    { url = "*/", fg = "#cacb77" },
]

# : ]]]
