cursor            #ffb3b4
cursor_text_color #561d22

foreground            #f0dede
background            #140c0c
selection_foreground  #44292a
selection_background  #e6bdbd
url_color             #e6bdbd

#: black 000000 767676
color0  #1a1111
color8  #3d3232
#: red cc0403 f2201f
color1  #30110e
color9  #a83a2f
#: green 19cb00 23fd00
color2  #e6bdbd
color10 #ffdada
#: yellow cecb00 fffd00
color3  #e6c18d
color11 #ffddb0
#: blue 0d73cc 1a8fff
color4  #733337
color12 #ffb3b4
#: magenta cb1ed1 fd28ff
color5  #5d3f40
color13 #e6bdbd
#: cyan 0dcdcd 14ffff
color6  #5b421a
color14 #e6c18d
#: white dddddd ffffff
color7  #d7c1c1
color15 #f0dede

mark1_foreground #3b080e
mark1_background #ffdada
mark2_foreground #2c1516
mark2_background #ffdada
mark3_foreground #281800
mark3_background #ffddb0

active_tab_foreground #561d22
active_tab_background #ffb3b4
inactive_tab_foreground #ffdada
inactive_tab_background #733337

active_border_color #ffb3b4
inactive_border_color #561d22
# bell_border_color #ff5a00
