cursor            #cacb77
cursor_text_color #323200

foreground            #e6e3d5
background            #0f0f07
selection_foreground  #313219
selection_background  #cac8a5
url_color             #cac8a5

#: black 000000 767676
color0  #14140c
color8  #36352c
#: red cc0403 f2201f
color1  #503f6a
color9  #9c89b9
#: green 19cb00 23fd00
color2  #cac8a5
color10 #e6e4c0
#: yellow cecb00 fffd00
color3  #a4d0be
color11 #bfecd9
#: blue 0d73cc 1a8fff
color4  #484a00
color12 #cacb77
#: magenta cb1ed1 fd28ff
color5  #48482d
color13 #cac8a5
#: cyan 0dcdcd 14ffff
color6  #254e40
color14 #a4d0be
#: white dddddd ffffff
color7  #c9c7b6
color15 #e6e3d5

mark1_foreground #1c1d00
mark1_background #e6e790
mark2_foreground #1c1d06
mark2_background #e6e4c0
mark3_foreground #002117
mark3_background #bfecd9

active_tab_foreground #323200
active_tab_background #cacb77
inactive_tab_foreground #e6e790
inactive_tab_background #484a00

active_border_color #cacb77
inactive_border_color #323200
# bell_border_color #ff5a00
