cursor            #ffb3b3
cursor_text_color #561d21

foreground            #f0dede
background            #140c0c
selection_foreground  #44292a
selection_background  #e6bdbc
url_color             #e6bdbc

#: black 000000 767676
color0  #1a1111
color8  #3d3232
#: red cc0403 f2201f
color1  #7b1e44
color9  #d75b8d
#: green 19cb00 23fd00
color2  #e6bdbc
color10 #ffdad9
#: yellow cecb00 fffd00
color3  #e5c18d
color11 #ffddaf
#: blue 0d73cc 1a8fff
color4  #733336
color12 #ffb3b3
#: magenta cb1ed1 fd28ff
color5  #5d3f3f
color13 #e6bdbc
#: cyan 0dcdcd 14ffff
color6  #5b421a
color14 #e5c18d
#: white dddddd ffffff
color7  #d7c1c1
color15 #f0dede

mark1_foreground #3b080d
mark1_background #ffdad9
mark2_foreground #2c1515
mark2_background #ffdad9
mark3_foreground #281800
mark3_background #ffddaf

active_tab_foreground #561d21
active_tab_background #ffb3b3
inactive_tab_foreground #ffdad9
inactive_tab_background #733336

active_border_color #ffb3b3
inactive_border_color #561d21
# bell_border_color #ff5a00
